import {test,expect} from '@playwright/test';
const name='Gentle Cream Cleanser';
async function add(page){await page.goto('/shop');await page.getByRole('button',{name:`Add ${name} to bag`,exact:true}).click();await page.getByRole('link',{name:'Bag (1)'}).click();}
test('SMOKE-001 homepage loads without fatal JavaScript errors',async({page})=>{const errors=[];page.on('pageerror',error=>errors.push(error.message));await page.goto('/');await expect(page.getByRole('heading',{name:'Feel good. Glow your way.'})).toBeVisible();expect(errors).toEqual([]);});
test('SMOKE-002 catalogue renders 30 products and detail',async({page})=>{await page.goto('/shop');await expect(page.locator('.product')).toHaveCount(30);await page.getByRole('heading',{name,exact:true}).click();await expect(page.getByRole('heading',{name,exact:true})).toBeVisible();await expect(page.getByText(/Mock product for/)).toBeVisible();});
test('SMOKE-003 search locates product and handles no results',async({page})=>{await page.goto('/shop');await page.getByRole('searchbox').fill('Vitamin C');await expect(page.locator('.product')).toHaveCount(1);await expect(page.getByRole('heading',{name:'Vitamin C Serum'})).toBeVisible();await page.getByRole('searchbox').fill('nonexistent');await expect(page.getByText(/No products match/)).toBeVisible();});
test('SMOKE-004 category filters products',async({page})=>{await page.goto('/shop');await page.getByLabel('Category',{exact:true}).selectOption('Makeup');await expect(page.locator('.product')).toHaveCount(8);await expect(page.locator('.product .category')).toHaveText(Array(8).fill('Makeup'));});
test('SMOKE-005 add to cart persists on refresh',async({page})=>{await add(page);await expect(page.locator('.cart-item')).toHaveCount(1);await page.reload();await expect(page.locator('.cart-item')).toHaveCount(1);});
test('SMOKE-006 quantity increases and decreases',async({page})=>{await add(page);await page.getByRole('button',{name:`Increase ${name}`}).click();await expect(page.getByLabel('Quantity',{exact:true})).toHaveText('2');await page.getByRole('button',{name:`Decrease ${name}`}).click();await expect(page.getByLabel('Quantity',{exact:true})).toHaveText('1');});
test('SMOKE-007 removal shows empty cart',async({page})=>{await add(page);await page.getByRole('button',{name:'Remove',exact:true}).click();await expect(page.getByRole('heading',{name:'Your bag is empty'})).toBeVisible();await expect(page.getByRole('link',{name:'Bag (0)'})).toBeVisible();});
test('SMOKE-008 subtotal reflects quantity and multiple items',async({page})=>{await add(page);await expect(page.getByTestId('subtotal')).toContainText('149');await page.getByRole('button',{name:`Increase ${name}`}).click();await expect(page.getByTestId('subtotal')).toContainText('298');await page.getByRole('link',{name:'Shop',exact:true}).click();await page.getByRole('button',{name:'Add Rosewater Toner to bag',exact:true}).click();await page.getByRole('link',{name:'Bag (3)'}).click();await expect(page.getByTestId('subtotal')).toContainText('427');});
test('SMOKE-009 mobile layout and cart remain usable',async({page})=>{await page.setViewportSize({width:375,height:812});await page.goto('/');await expect(page.locator('.product')).toHaveCount(30);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'qa/mobile-home.png',fullPage:true});await add(page);await expect(page.getByRole('button',{name:`Increase ${name}`})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});
test('SMOKE-010 unknown route and product fail gracefully',async({page})=>{for(const path of ['/missing','/product/missing']){await page.goto(path);await expect(page.getByRole('heading',{name:'Page not found'})).toBeVisible();await page.getByRole('link',{name:'Back to home'}).click();await expect(page.getByRole('heading',{name:'Feel good. Glow your way.'})).toBeVisible();}await page.screenshot({path:'qa/desktop-home.png',fullPage:true});});
